DROP TABLE `acl_role_bkp`;
DROP TABLE `catalog_attribute_link_sportsacessories_composition`;
DROP TABLE `catalog_attribute_link_sportsapparel_composition`;
DROP TABLE `catalog_attribute_option_apparel_character`;
DROP TABLE `catalog_attribute_option_babies_character`;
DROP TABLE `catalog_attribute_option_sportsacessories_composition`;
DROP TABLE `catalog_attribute_option_sportsapparel_composition`;
DROP TABLE `catalog_attribute_option_sportsequipment_producttype`;
DROP TABLE `catalog_config_babies`;
DROP TABLE `catalog_config_sportsequipment`;
DROP TABLE `erp_freight_table_new`;
DROP TABLE `migrations`;
DROP TABLE `personal_access_tokens`;
DROP TABLE `tracking_data`;
DROP TABLE `users`;
ALTER TABLE `catalog_config` DROP COLUMN `ncmm`;
ALTER TABLE `catalog_config` DROP COLUMN `quantidadavalacao`;
ALTER TABLE `catalog_config` DROP COLUMN `quantity_rating_1`;
ALTER TABLE `catalog_config` DROP COLUMN `quantity_rating_2`;
ALTER TABLE `catalog_config` DROP COLUMN `rating`;
ALTER TABLE `catalog_config` DROP COLUMN `ratingnew`;
ALTER TABLE `catalog_config` DROP COLUMN `ratingnewtwo`;
ALTER TABLE `catalog_config` DROP COLUMN `teste`;
ALTER TABLE `catalog_config_home` DROP COLUMN `depth`;
ALTER TABLE `catalog_config_home` DROP COLUMN `height`;
ALTER TABLE `catalog_config_home` DROP COLUMN `width`;
ALTER TABLE `catalog_config_sportsapparel` DROP COLUMN `fk_catalog_attribute_option_sportsapparel_composition`;
ALTER TABLE `catalog_config_sportsapparel` DROP COLUMN `fk_catalog_attribute_option_sportsapparel_occasion`;
ALTER TABLE `catalog_config_sportsapparel` DROP COLUMN `fk_catalog_attribute_option_sportsapparel_states_teams`;
ALTER TABLE `catalog_config_sportsapparel` DROP COLUMN `fk_catalog_attribute_option_sportsapparel_teams`;
ALTER TABLE `catalog_config_sportsshoes` DROP COLUMN `fk_catalog_attribute_option_sportsshoes_occasion`;
ALTER TABLE `catalog_config_sportsshoes` DROP COLUMN `fk_catalog_attribute_option_sportsshoes_states_teams`;
ALTER TABLE `catalog_config_sportsshoes` DROP COLUMN `fk_catalog_attribute_option_sportsshoes_teams`;
ALTER TABLE `boleto_reconciliation` ADD `bank_name` varchar(255);
ALTER TABLE `boleto_reconciliation` ADD `order_number_bkp` int;
ALTER TABLE `boleto_reconciliation` ADD `our_number` bigint;
ALTER TABLE `cancellationletter_order_log` ADD `cashback_is_reversed` tinyint;
ALTER TABLE `catalog_category_sellercenter_migration` ADD `dafitinew_id` int;
ALTER TABLE `catalog_category_sellercenter_migration` ADD `kanuinew_id` int;
ALTER TABLE `catalog_category_sellercenter_migration` ADD `tricaenew_id` int;
ALTER TABLE `catalog_config` ADD `fk_catalog_attribute_option_global_additional_ship_days` int;
ALTER TABLE `catalog_config` ADD `fk_catalog_attribute_option_global_character` int;
ALTER TABLE `catalog_config` ADD `fk_catalog_attribute_option_global_origincountry` int;
ALTER TABLE `catalog_config` ADD `fk_catalog_attribute_option_global_warranty` int;
ALTER TABLE `catalog_config` ADD `observacoes_importantes` text;
ALTER TABLE `catalog_config` ADD `plus_size` tinyint;
ALTER TABLE `catalog_config` ADD `produto_exclusivo_dafiti` tinyint;
ALTER TABLE `catalog_config` ADD `registro_do_produto` varchar(50);
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_country_teams` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_depth` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_doors_amount` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_drawers_amount` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_environment` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_height` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_international_teams` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_kit` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_materialtype` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_mirror` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_national_teams` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_numberofpiecesfilter` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_patterning` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_product_type` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_shape` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_volt` int;
ALTER TABLE `catalog_config_home` ADD `fk_catalog_attribute_option_home_width` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `composition` varchar(255);
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_activityfilter` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_clothes_material` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_fit` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_kit` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_league` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_length` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_modelfilter` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_neckline` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_print` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_sleeve` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_specifications` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_style` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_waist` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_washing` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `fk_catalog_attribute_option_sportsapparel_washing_type` int;
ALTER TABLE `catalog_config_sportsapparel` ADD `measurements` varchar(255);
ALTER TABLE `catalog_config_sportsshoes` ADD `composition` varchar(255);
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_activityfilter` int;
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_closing` int;
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_heel_height` int;
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_kit` int;
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_model` int;
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_shaft_height` int;
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_shoe_type` int;
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_style` int;
ALTER TABLE `catalog_config_sportsshoes` ADD `fk_catalog_attribute_option_sportsshoes_tip_shape` int;
ALTER TABLE `sales_order_item` ADD `erp_id_old` int;
ALTER TABLE `seller` ADD `bank_account` varchar(20);
ALTER TABLE `seller` ADD `bank_account_type` char(2);
ALTER TABLE `seller` ADD `bank_agency` varchar(10);
ALTER TABLE `seller` ADD `bank_number` varchar(5);
ALTER TABLE `seller` ADD `state` char(2);
ALTER TABLE `seller` ADD `tax_id` varchar(14);